id: P010393
initial_creation_type: ocr
source_metadata:
  id: bdr:W29278
  title: ཀློང་ཆེན་སྙིང་ཐིག་གི་ལོ་རྒྱུས་གསལ་བའི་མེ་ལོང་།
  author: ''
  volumes:
    b89220580a53456ea602a4360136d570:
      image_group_id: I1KG10563
      title: ''
      volume_number: 1
      total_pages: 289
      base_file: v001.txt
