id: P010393
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:47:29.132388
source_metadata:
  id: bdr:W29278
  title: ཀློང་ཆེན་སྙིང་ཐིག་གི་ལོ་རྒྱུས་གསལ་བའི་མེ་ལོང་།
  author: ''
  volumes:
    b89220580a53456ea602a4360136d570:
      image_group_id: I1KG10563
      title: ''
      volume_number: 1
      total_pages: 289
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
