id: I9609D679
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:52:46+00:00'
last_modified: '2022-06-08T13:16:06.615957+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29278
  title: ཀློང་ཆེན་སྙིང་ཐིག་གི་ལོ་རྒྱུས་གསལ་བའི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7606':
      image_group_id: I1KG10563
      title: ''
      total_pages: 289
      order: 1
      base_file: 7606.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
