id: I9609D679
legacy_id: P010393
ocr_import_info:
  bdrc_scan_id: W29278
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T22:51:10'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T10:22:02.230131+00:00'
last_modified: 2022-09-02 18:22:20.331665
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29278
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW29278
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀློང་ཆེན་སྙིང་ཐིག་གི་ལོ་རྒྱུས་གསལ་བའི་མེ་ལོང་།
  author: དྲག་ཀྲར་ཀརྨ་དབང་ཕྱུག
statistics:
  ocr_word_mean_confidence_index: 0.909819266810964
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG10563:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10563
      total_pages: 289
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10563.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.909819266810964
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
